"""Emit an idempotent D1 backfill for canonical Gym, Bank, and Store brands.

Run after migrations/0010_brand_aware_nearby.sql, without re-importing the
country dataset:

  for type in gym bank store; do
    for prefix in 0 1 2 3 4 5 6 7 8 9 a b c d e f; do
      python3 cloudflare/extraction/backfill_brands.py --poi-type "$type" --id-prefix "$prefix" > "/tmp/brand-backfill-$type-$prefix.sql"
      (cd cloudflare && npx wrangler d1 execute brush-poi-registry --remote --file="/tmp/brand-backfill-$type-$prefix.sql")
    done
  done

Each prefix is a separate D1 import because a whole-country normalization
statement exceeds D1's remote memory limit. The operations are idempotent and
guarded by the same prefix on the update target.

The canonical values and aliases come directly from the shared app/import/API
catalogue. A matching update always writes the canonical `name`; unmatched
Gym/Bank records retain their source value so they remain available for the
next catalogue review.
"""
import argparse
import json
import os

from classify_and_load import normalize_text

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DICTIONARY_PATH = os.path.join(ROOT, 'src', 'constants', 'brandDictionary.json')


def sql_string(value):
    return "'" + value.replace("'", "''") + "'"


def brand_case(entries, normalized_column='normalized_name'):
    clauses = []
    for entry in entries:
        for alias in [entry['name'], *entry.get('aliases', [])]:
            normalized_alias = normalize_text(alias)
            if not normalized_alias:
                continue
            # Same padded word/phrase boundary used by find_brand: "BPI" must
            # not match inside a longer unrelated name, while "Banco BPI"
            # remains a valid phrase match after punctuation/accent folding.
            clauses.append(
                f"WHEN (' ' || {normalized_column} || ' ') LIKE "
                f"{sql_string('% ' + normalized_alias + ' %')} THEN {sql_string(entry['name'])}",
            )
    return '\n      '.join(clauses)


HEX_ID_PREFIXES = '0123456789abcdef'


def hex_id_prefix(value):
    normalized = value.lower()
    if not normalized or any(character not in HEX_ID_PREFIXES for character in normalized):
        raise argparse.ArgumentTypeError('id prefix must contain only hexadecimal characters')
    return normalized


def emit_for_foursquare(poi_type, entries, id_prefix=None):
    where_clause = f"""EXISTS (
    SELECT 1 FROM poi_type
    WHERE poi_type.fsq_place_id = target.fsq_place_id
      AND poi_type.poi_type = {sql_string(poi_type)}
)"""
    if id_prefix is not None:
        where_clause += f"\n  AND target.fsq_place_id LIKE {sql_string(id_prefix + '%')}"
    print(f"""UPDATE poi AS target
SET brand = CASE
      {brand_case(entries, 'target.dedupe_name')}
      -- Preserve a source value that is not in this curated catalogue. It is
      -- evidence for the next bank-review pass, not a reason to erase data.
      ELSE target.brand
    END
WHERE {where_clause};""")


def emit_for_curated(poi_type, entries, id_prefix=None):
    where_clause = f"target.primary_poi_type = {sql_string(poi_type)}"
    if id_prefix is not None:
        where_clause += f" AND target.poi_id LIKE {sql_string(id_prefix + '%')}"
    print(f"""UPDATE curated_poi AS target
SET brand = CASE
      {brand_case(entries, 'target.dedupe_name')}
      ELSE target.brand
    END
WHERE {where_clause};""")


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument('--poi-type', choices=('gym', 'bank', 'store'), action='append')
    parser.add_argument('--id-prefix', type=hex_id_prefix)
    args = parser.parse_args(argv)

    with open(DICTIONARY_PATH) as source:
        dictionary = json.load(source)
    print('-- Generated by extraction/backfill_brands.py. Do not hand-edit.')
    for poi_type in args.poi_type or ('gym', 'bank', 'store'):
        entries = dictionary[poi_type]
        # D1 cannot materialise the full normalisation CTE for every global
        # POI type at once. Foursquare and curated UUID ids are hex, so split
        # into small deterministic batches without changing matching logic.
        for prefix in (args.id_prefix or HEX_ID_PREFIXES):
            emit_for_foursquare(poi_type, entries, prefix)
            emit_for_curated(poi_type, entries, prefix)
    print("""-- Backfill report: capture these result rows with the deployment record.
SELECT poi_type.poi_type, poi.brand, COUNT(*) AS places
FROM poi_type
JOIN poi ON poi.fsq_place_id = poi_type.fsq_place_id
WHERE poi_type.poi_type IN ('gym', 'bank', 'store')
GROUP BY poi_type.poi_type, poi.brand
ORDER BY poi_type.poi_type, places DESC, poi.brand;

SELECT primary_poi_type AS poi_type, brand, COUNT(*) AS places
FROM curated_poi
WHERE primary_poi_type IN ('gym', 'bank', 'store')
GROUP BY primary_poi_type, brand
ORDER BY primary_poi_type, places DESC, brand;""")


if __name__ == '__main__':
    main()
