"""KAN-455. Hide the `Casa …` rows the padded brand match promoted as home stores.

    python3 hide_casa_word_matches.py --overture <archive.csv> --overture-key <r2 key> \
        --out-sql ../migrations/0044_hide_casa_word_matches.sql --out-tsv ../../docs/kan-455/casa-word-matches.tsv

Before KAN-448 rule 5, `Casa` — a homeware chain — matched as a padded word,
so every generic-shopping `Casa das Dores`, `Casa do Povo`, `A Casa da Sopa`
in Portugal was promoted as `store`/`home`. Rule 5 stopped that for new
promotions; the rows already promoted are still served. Under the current
rules they are `pending` — unresolved, which is what they are — and the
honest correction is to stop serving them, not to invent a type.

The selection is the decision, not the name:

  (a) the archive row's category is generic (`''` or `shopping`) and
      `decide()` under the current rules leaves it `pending` — so nothing
      today would promote it; a `Casa …` whose category says home_goods is
      promoted by that category and is not selected;
  (b) prod currently serves it as `store` with `store_kind = home` — fetched
      for exactly the ids (a) chose, ≤150 per read.

Both must hold. The output is `INSERT OR IGNORE` into `poi_source_correction`
(`source = 'overture'`, `visible = 0`), the KAN-452 removal path nearby
already honours, one statement per ≤150 rows. No row is deleted; a reviewer
who disagrees flips `visible` back. Executes nothing itself.
"""
import argparse
import os
import sys
from datetime import date

EXTRACTION_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, EXTRACTION_DIR)
os.environ.setdefault('BRUSH_TYPE_RELATION', 'sql')

import promote_overture_candidates as promote
from analyse_poi_candidates import reachable_types
from backfill_chain_brands import query, reviewed_overrides
from classify_and_load import normalize_text, sql_escape

BATCH = 150
WORD = 'casa'
REVIEW_NOTE = 'KAN-455: padded "Casa" brand match promoted a generic-shopping row as store/home; pending under KAN-448 rule 5'


def has_word(name, word=WORD):
    return f' {word} ' in f' {normalize_text(name or "")} '


def pending_word_rows(overture_csv, overture_key, word=WORD):
    """(a): generic-category archive rows carrying the word that the current
    rules leave pending. Returns {overture_id: name}."""
    import csv

    mapping, reachable, brands = promote.category_map(), reachable_types(), promote.load_brand_dictionary()
    kinds, cuisines = promote.store_kind_alias_index(), promote.food_cuisine_alias_index()
    financial, store_brands = promote.load_financial_service_name_rules(), promote.store_brand_index()
    overrides = reviewed_overrides(overture_key)
    selected = {}
    with open(overture_csv, newline='') as handle:
        for row in csv.DictReader(handle):
            if (row['category'] or '') not in promote.GENERIC_CATEGORIES or not has_word(row['name'], word):
                continue
            status, _types, _attributes, _reason = promote.decide(
                row, mapping, reachable, brands, kinds, cuisines, financial, store_brands, overrides)
            if status == 'pending':
                selected[row['overture_id']] = row['name']
    return selected


def served_as_home(ids):
    """(b): of exactly these ids, the ones prod serves as store/home, with
    their served name. ≤150 ids per read."""
    served = {}
    ids = list(ids)
    for start in range(0, len(ids), BATCH):
        chunk = ','.join(sql_escape(i) for i in ids[start:start + BATCH])
        rows = query(
            "SELECT p.overture_id, p.name, p.primary_poi_type, "
            "(SELECT group_concat(a.value) FROM overture_poi_attribute a WHERE a.overture_id = p.overture_id AND a.dimension = 'store_kind') AS kinds "
            f"FROM overture_poi p WHERE p.overture_id IN ({chunk})")
        for row in rows:
            kinds = (row['kinds'] or '').split(',')
            if row['primary_poi_type'] == 'store' and kinds == ['home']:
                served[row['overture_id']] = row['name']
    return served


def statements(ids, note=REVIEW_NOTE, created_at=None):
    created_at = created_at or date.today().isoformat()
    ids = sorted(ids)
    for start in range(0, len(ids), BATCH):
        values = ',\n'.join(
            f"('overture',{sql_escape(i)},0,{sql_escape(note)},{sql_escape(created_at)})"
            for i in ids[start:start + BATCH])
        yield ('INSERT OR IGNORE INTO poi_source_correction (source, source_id, visible, review_note, created_at) VALUES\n'
               f'{values};\n')


def header(count, generated_from):
    return (
        '-- KAN-455. Hide the generic-shopping rows a padded "Casa" brand match\n'
        '-- promoted as store/home before KAN-448 rule 5. Generated by\n'
        f'-- hide_casa_word_matches.py from the archived Portugal source ({generated_from});\n'
        "-- selection = decide() leaves the row pending AND prod serves it as store/home,\n"
        '-- both by exact id. poi_source_correction (visible = 0) is the KAN-452 removal\n'
        '-- path nearby already honours; no row is deleted. Idempotent.\n'
        f'-- {count:,} rows hidden.\n')


def run(overture_csv, overture_key, out_sql, out_tsv):
    candidates = pending_word_rows(overture_csv, overture_key)
    print(f'{len(candidates):,} generic-category "{WORD}" rows are pending under the current rules', file=sys.stderr)
    served = served_as_home(candidates)
    print(f'{len(served):,} of them are served by prod as store/home', file=sys.stderr)
    with open(out_sql, 'w') as handle:
        handle.write(header(len(served), os.path.basename(overture_key)))
        handle.writelines(statements(served))
    os.makedirs(os.path.dirname(out_tsv) or '.', exist_ok=True)
    with open(out_tsv, 'w') as handle:
        handle.write('overture_id\tname\n')
        for overture_id in sorted(served):
            handle.write(f'{overture_id}\t{served[overture_id]}\n')
    not_served = sorted(set(candidates) - set(served))
    if not_served:
        print(f'{len(not_served):,} pending candidates are not served as store/home and are left alone', file=sys.stderr)
    print(f'{len(served):,} rows -> {out_sql}, {out_tsv}', file=sys.stderr)
    return 0


def main(argv):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--overture', required=True, help='archived Overture CSV')
    parser.add_argument('--overture-key', required=True, help='its R2 key — the overrides are scoped to it')
    parser.add_argument('--out-sql', required=True)
    parser.add_argument('--out-tsv', required=True)
    args = parser.parse_args(argv)
    return run(args.overture, args.overture_key, args.out_sql, args.out_tsv)


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
