"""KAN-446. One command: the residual evidence join for a country.

    python3 run_evidence_join.py --country ES
    python3 run_evidence_join.py --country ES --emit \
        --overture-key overture-country-sources/ES/<run>.csv \
        --source-key country-sources-unfiltered/ES/<uuid>.csv \
        --osm-key archives/osm-retail/ES/<run>.tsv

Deterministic evidence generation, locally. The output goes into a PR, is
reviewed, merged and deployed, and only then does promotion read it. This
command never calls promotion, never writes D1 and never posts a metric: the
one write it makes is archiving the extracted OSM retail TSV under
`archives/osm-retail/`, so a rerun does not depend on Geofabrik still serving
the same file.

Dry-run by default. Without `--emit` it resolves inputs, runs the join, prints
the counts, and writes nothing. `--emit` requires the Overture and Foursquare
keys explicitly: dry-run may discover and *print* the newest, but an emitted
run must say which object it used, or it cannot be reproduced. OSM needs no
key on a country's first run — the Geofabrik extract is pinned and archived,
and the manifest records the key every later run passes as `--osm-key`.

The residual is derived here, from the archived Overture CSV plus the current
overrides plus the real promotion decision. KAN-444 started from an inventory
file nobody had generated by tracked code; a country that has never been
audited has no such file, and this is what makes one command true for it.

Matching is `match_residual_foursquare` and `match_residual_osm`, unchanged
and shared. The rule is name plus distance, never the provider's category;
conflicting kinds among matches leave a row unresolved rather than picking the
nearest branch.
"""
import argparse
import csv
import datetime
import hashlib
import io
import json
import os
import subprocess
import sys
import tempfile
import urllib.request
from collections import Counter, defaultdict

# Reachability from the committed type relation, never from live D1: a PR is
# validated against what the repo declares, and CI has no Cloudflare token.
os.environ.setdefault('BRUSH_TYPE_RELATION', 'sql')

EXTRACTION_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, EXTRACTION_DIR)
CLOUDFLARE_DIR = os.path.dirname(EXTRACTION_DIR)
ROOT = os.path.dirname(CLOUDFLARE_DIR)

import match_residual_foursquare as fsq
import match_residual_osm as osm
import promote_overture_candidates as promote
from analyse_poi_candidates import reachable_types

OVERRIDES_PATH = os.path.join(CLOUDFLARE_DIR, 'src', 'overtureCandidateOverrides.json')
# Anything promotion reads to decide a row. The brand dictionary lives on the
# app side (KAN-340 reused it rather than keeping a second list) and a brand
# added there changes which rows are residual at all.
CONFIG_FILES = ('src/overtureCategories.json', 'src/storeSubtypeCategories.json',
                '../src/constants/storeSubtypeDictionary.json')
EVIDENCE_DIR = os.path.join(ROOT, 'docs', 'evidence')
R2_BUCKET = 'brush-poi-exports'

GEOFABRIK = {
    'PT': 'europe/portugal', 'ES': 'europe/spain', 'FR': 'europe/france', 'IT': 'europe/italy',
    'DE': 'europe/germany', 'GB': 'europe/great-britain', 'IE': 'europe/ireland', 'NL': 'europe/netherlands',
    'BE': 'europe/belgium', 'AT': 'europe/austria', 'CH': 'europe/switzerland',
}


class EmitRefused(RuntimeError):
    """`--emit` without an explicit input key. Reproducibility is the point."""


# --------------------------------------------------------------------------- inputs

def sha256_of(path):
    digest = hashlib.sha256()
    with open(path, 'rb') as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b''):
            digest.update(chunk)
    return digest.hexdigest()


def sha256_bytes(data):
    return hashlib.sha256(data).hexdigest()


def r2_get(key, local_path):
    subprocess.run(
        ['npx', 'wrangler', 'r2', 'object', 'get', f'{R2_BUCKET}/{key}', '--remote', '--file', local_path],
        cwd=CLOUDFLARE_DIR, check=True, capture_output=True, text=True)
    return local_path


def r2_put(local_path, key):
    subprocess.run(
        ['npx', 'wrangler', 'r2', 'object', 'put', f'{R2_BUCKET}/{key}', '--remote', '--file', local_path],
        cwd=CLOUDFLARE_DIR, check=True, capture_output=True, text=True)
    return key


def r2_list(prefix, worker_url, secret):
    """Discovery through the internal endpoint; wrangler cannot list keys."""
    objects, cursor = [], None
    while True:
        query = f'prefix={urllib.request.quote(prefix, safe="")}&limit=1000'
        if cursor:
            query += f'&cursor={urllib.request.quote(cursor, safe="")}'
        request = urllib.request.Request(f'{worker_url}/internal/r2/list?{query}',
                                         headers={'X-Build-Secret': secret})
        with urllib.request.urlopen(request, timeout=60) as response:
            page = json.load(response)
        objects.extend(page['objects'])
        cursor = page.get('cursor')
        if not page.get('truncated') or not cursor:
            return objects


def newest(objects):
    return max(objects, key=lambda o: o['uploaded'])['key'] if objects else None


def geofabrik_pbf(country_code, work_dir):
    """Download the country PBF and record what Geofabrik said it was."""
    path = GEOFABRIK.get(country_code.upper())
    if not path:
        raise ValueError(f'no Geofabrik path known for {country_code}; pass --osm-key or --pbf')
    url = f'https://download.geofabrik.de/{path}-latest.osm.pbf'
    local = os.path.join(work_dir, f'{country_code}.osm.pbf')
    with urllib.request.urlopen(url, timeout=120) as response, open(local, 'wb') as handle:
        last_modified = response.headers.get('Last-Modified')
        for chunk in iter(lambda: response.read(1 << 20), b''):
            handle.write(chunk)
    return local, {'url': url, 'last_modified': last_modified, 'sha256': sha256_of(local)}


# --------------------------------------------------------------------------- residual

def residual_rows(overture_csv, overture_key, reaudit_prefix=None):
    """Generic-shopping rows the real promotion decision leaves pending.

    Exactly the decision run_overture_country makes, with the current
    overrides applied, so a row already decided in any reviewed batch is
    never re-audited and a row a name rule would promote is never joined.

    `reaudit_prefix` ignores batches whose name starts with it, which puts
    a previous run's rows back into the residual. That is how a run is
    reproduced against its predecessor, and it is never used to emit.
    """
    mapping, reachable, brands = promote.category_map(), reachable_types(), promote.load_brand_dictionary()
    kinds, cuisines = promote.store_kind_alias_index(), promote.food_cuisine_alias_index()
    financial, store_brands = promote.load_financial_service_name_rules(), promote.store_brand_index()
    with open(OVERRIDES_PATH) as handle:
        source = json.load(handle).get(overture_key, {})
    overrides = {poi_id: entry for name, batch in source.items()
                 if not (reaudit_prefix and name.startswith(reaudit_prefix))
                 for poi_id, entry in batch.items()}
    with open(overture_csv, newline='') as handle:
        for row in csv.DictReader(handle):
            if row.get('category') != 'shopping':
                continue
            status, _, _, _ = promote.decide(row, mapping, reachable, brands, kinds, cuisines,
                                             financial, store_brands, overrides)
            if status == 'pending':
                yield row


# --------------------------------------------------------------------------- join

def join(rows, foursquare_csv, osm_tsv):
    """Every residual row through both passes. Returns suggestions and counts."""
    fsq_grid, _, _ = fsq.load_foursquare(foursquare_csv)
    index = fsq.subtype_index()
    osm_grid, _ = osm.load_osm(osm_tsv)
    suggestions, counts = [], Counter()
    for row in rows:
        locality = row.get('locality') or ''
        if not (row.get('lat') and row.get('lng')):
            # Nothing to match on location with. Unresolved, and said so.
            counts[('insufficient_evidence', '')] += 1
            suggestions.append({
                'overture_id': row['overture_id'], 'name': row['name'], 'locality': locality,
                'lat': None, 'lng': None, 'candidates': [], 'decision': 'insufficient_evidence',
                'poi_type': '', 'store_kind': '', 'reason': 'no coordinates in the Overture archive', 'source': ''})
            continue
        lat, lng = float(row['lat']), float(row['lng'])
        record = {
            'overture_id': row['overture_id'], 'name': row['name'], 'locality': locality,
            'lat': round(lat, 6), 'lng': round(lng, 6), 'candidates': [],
        }
        decision, subtype, reason, matches = fsq.decide(row['name'], lat, lng, fsq_grid, index, locality)
        record['candidates'] += [
            {'source': 'foursquare', 'id': m[0], 'name': m[1], 'distance_m': round(m[2]),
             'similarity': round(m[3], 2), 'exact': m[4], 'categories': m[5]} for m in matches]
        source = 'foursquare'
        poi_type, store_kind = ('store', subtype) if decision == 'verified_subtype' else ('', '')
        if decision == 'insufficient_evidence':
            o_decision, o_type, o_kind, o_reason, o_matches = osm.decide(row['name'], lat, lng, osm_grid, locality)
            record['candidates'] += [
                {'source': 'osm', 'id': m[0], 'name': m[1], 'distance_m': round(m[2]),
                 'similarity': round(m[3], 2), 'exact': m[4], 'family': m[5]} for m in o_matches]
            if o_decision != 'insufficient_evidence':
                decision, poi_type, store_kind, reason, source = o_decision, o_type, o_kind, o_reason, 'osm'
            else:
                reason, source = f'{reason}; {o_reason}', ''
        record.update({'decision': decision, 'poi_type': poi_type, 'store_kind': store_kind,
                       'reason': reason, 'source': source})
        counts[(decision, source)] += 1
        suggestions.append(record)
    return suggestions, counts


def overrides_draft(suggestions, overture_key, run_id):
    """Only the decided rows, in the shape promotion reads, one batch per type."""
    batches = defaultdict(dict)
    for record in suggestions:
        if record['decision'] == 'insufficient_evidence':
            continue
        where = 'Foursquare' if record['source'] == 'foursquare' else 'OSM'
        if record['decision'] == 'excluded':
            batches[f'evidence_{run_id}_exclusions'][record['overture_id']] = {
                'decision': 'rejected', 'reason': f'{where} match shows this is not a consumer store'}
            continue
        kind = record['store_kind']
        entry = {'poi_type': record['poi_type'], 'reason': f'{where} name and location match'}
        if kind:
            entry['store_kind'] = kind
        batches[f"evidence_{run_id}_{'store_' + kind if kind else record['poi_type']}"][record['overture_id']] = entry
    return {overture_key: dict(batches)}


def residual_report(counts, total):
    by_state = Counter()
    by_source = Counter()
    for (decision, source), n in counts.items():
        by_state[decision] += n
        if source:
            by_source[source] += n
    return {
        'residual_rows': total,
        'by_state': {k: {'rows': v, 'share': round(v / total, 4) if total else 0} for k, v in by_state.items()},
        'resolved_by_source': dict(by_source),
    }


# --------------------------------------------------------------------------- provenance

def config_hash():
    """Anything that changes a decision. A different hash is a different tool."""
    digest = hashlib.sha256()
    digest.update(repr((fsq.MATCH_LADDER, fsq.FAR_M, fsq.LEGAL_SUFFIXES, fsq.LEAF_ALIASES,
                        fsq.EXCLUDING_LEAVES, fsq.GENERIC_LEAVES, fsq.GENERIC_SUBTYPES)).encode())
    digest.update(repr((osm.SHOP_TO_TYPE, osm.AMENITY_TO_TYPE, osm.CRAFT_TO_TYPE,
                        osm.HEALTHCARE_TO_TYPE, osm.GENERIC_SHOP_VALUES)).encode())
    for relative in CONFIG_FILES:
        with open(os.path.join(CLOUDFLARE_DIR, relative), 'rb') as handle:
            digest.update(handle.read())
    return digest.hexdigest()


def repo_commit():
    try:
        return subprocess.run(['git', 'rev-parse', 'HEAD'], cwd=ROOT, check=True,
                              capture_output=True, text=True).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


def serialise(suggestions, draft, report):
    """The three outputs as bytes, so their hashes can go in the manifest."""
    lines = io.StringIO()
    for record in suggestions:
        lines.write(json.dumps(record, ensure_ascii=False, sort_keys=True) + '\n')
    return {
        'suggestions.jsonl': lines.getvalue().encode('utf-8'),
        'overrides-draft.json': (json.dumps(draft, ensure_ascii=False, indent=2) + '\n').encode('utf-8'),
        'residual-report.json': (json.dumps(report, indent=2) + '\n').encode('utf-8'),
    }


# --------------------------------------------------------------------------- run

def run(args):
    country = args.country.upper()
    run_id = args.run_id or datetime.datetime.now(datetime.timezone.utc).strftime('%Y%m%dT%H%M%SZ')
    # The two archive keys are choices among existing objects and must be
    # named. OSM is not a choice: without --osm-key the Geofabrik extract is
    # pinned by URL, Last-Modified and hash, and archived under a key the
    # manifest records, so the next run can name it.
    if args.emit and not (args.overture_key and args.source_key):
        raise EmitRefused('--emit requires --overture-key and --source-key')

    work_dir = args.work_dir or tempfile.mkdtemp(prefix=f'evidence-{country}-')
    os.makedirs(work_dir, exist_ok=True)
    discover = lambda prefix: r2_list(prefix, args.worker_url, args.secret) if args.worker_url and args.secret else []

    overture_key = args.overture_key or newest(discover(f'overture-country-sources/{country}/'))
    source_key = args.source_key or newest(discover(f'country-sources-unfiltered/{country}/'))
    if not overture_key or not source_key:
        raise SystemExit('could not resolve the Overture or Foursquare key; pass them explicitly '
                         'or set --worker-url and --secret for discovery')
    print(f'overture   {overture_key}\nfoursquare {source_key}', file=sys.stderr)

    overture_csv = r2_get(overture_key, os.path.join(work_dir, 'overture.csv'))
    foursquare_csv = r2_get(source_key, os.path.join(work_dir, 'foursquare.csv'))
    pins = {
        'overture': {'key': overture_key, 'sha256': sha256_of(overture_csv)},
        'foursquare': {'key': source_key, 'sha256': sha256_of(foursquare_csv)},
    }

    osm_tsv = os.path.join(work_dir, 'osm-retail.tsv')
    if args.osm_key:
        r2_get(args.osm_key, osm_tsv)
        pins['osm'] = {'archive_key': args.osm_key, 'sha256': sha256_of(osm_tsv)}
    else:
        import extract_osm_retail_pbf
        if args.pbf:
            pbf, pbf_pin = args.pbf, {'path': args.pbf, 'sha256': sha256_of(args.pbf)}
        else:
            pbf, pbf_pin = geofabrik_pbf(country, work_dir)
        extract_osm_retail_pbf.run(pbf, osm_tsv, os.path.join(work_dir, 'osm-report.json'))
        pins['osm'] = {'pbf': pbf_pin, 'sha256': sha256_of(osm_tsv),
                       'archive_key': f'archives/osm-retail/{country}/{run_id}.tsv'}

    if args.emit and args.reaudit_prefix:
        raise EmitRefused('--reaudit-prefix is for reproduction only; it cannot be emitted')
    rows = list(residual_rows(overture_csv, overture_key, args.reaudit_prefix))
    print(f'{len(rows):,} residual rows', file=sys.stderr)
    suggestions, counts = join(rows, foursquare_csv, osm_tsv)
    draft = overrides_draft(suggestions, overture_key, run_id)
    report = residual_report(counts, len(rows))
    for state, entry in sorted(report['by_state'].items(), key=lambda kv: -kv[1]['rows']):
        print(f"  {state:24s} {entry['rows']:>6,}  ({entry['share']:.1%})", file=sys.stderr)
    print(f"  resolved by source: {report['resolved_by_source']}", file=sys.stderr)

    if not args.emit:
        print('dry run: nothing written', file=sys.stderr)
        return 0

    outputs = serialise(suggestions, draft, report)
    manifest = {
        'country': country, 'run_id': run_id,
        'generated_at': datetime.datetime.now(datetime.timezone.utc).isoformat(),
        'tool_commit': repo_commit(), 'config_sha256': config_hash(),
        'inputs': pins,
        'outputs': {name: sha256_bytes(data) for name, data in outputs.items()},
    }
    out_dir = os.path.join(EVIDENCE_DIR, country, run_id)
    if os.path.exists(out_dir):
        # Runs are append-only. A reviewed run is never replaced in place;
        # a rerun is a new run id.
        raise SystemExit(f'refusing to overwrite an existing run: {out_dir}')
    # Archive first. The manifest names this key; a run directory must never
    # exist whose archive does not.
    if not args.osm_key:
        r2_put(osm_tsv, pins['osm']['archive_key'])
        print(f"archived OSM retail -> {pins['osm']['archive_key']}", file=sys.stderr)
    os.makedirs(out_dir)
    for name, data in outputs.items():
        with open(os.path.join(out_dir, name), 'wb') as handle:
            handle.write(data)
    with open(os.path.join(out_dir, 'manifest.json'), 'w') as handle:
        json.dump(manifest, handle, indent=2)
        handle.write('\n')
    print(f'-> {out_dir}', file=sys.stderr)
    return 0


def main(argv):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--country', required=True)
    parser.add_argument('--emit', action='store_true', help='write outputs; requires explicit keys')
    parser.add_argument('--overture-key')
    parser.add_argument('--source-key', help='unfiltered Foursquare archive key')
    parser.add_argument('--osm-key', help='archived OSM retail TSV key; skips the PBF')
    parser.add_argument('--pbf', help='local PBF instead of downloading from Geofabrik')
    parser.add_argument('--run-id')
    parser.add_argument('--reaudit-prefix', help='ignore batches with this prefix when deriving the residual (dry-run only)')
    parser.add_argument('--work-dir')
    parser.add_argument('--worker-url', default=os.environ.get('BRUSH_WORKER_URL'))
    parser.add_argument('--secret', default=os.environ.get('BUILD_TRIGGER_SECRET'))
    args = parser.parse_args(argv)
    try:
        return run(args)
    except EmitRefused as refused:
        print(f'refused: {refused}', file=sys.stderr)
        return 2


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
