-- KAN-392 — the 184 duplicate pairs the operator confirmed after the first
-- full Portugal OSM import (run 084e3511-abbd-43a2-9aed-d6a5e16c95d6).
--
-- Found by comparing all 307 per-scope rename reports: of 27,460 flagged
-- pairs, 265 had identical single-token identities once category words and
-- articles were stripped, and 184 of those were within 20 m. Every one was
-- reviewed and confirmed — 182 distinct OSM elements, 0.24% of the import.
--
-- Survivor rule: keep the Foursquare row, hide the OSM element. The
-- Foursquare name is already in the database and its record carries the
-- store attributes, so retaining it changes nothing else about the venue.
--
-- Recorded as a correction rather than a delete, per KAN-386: a later
-- Foursquare reload cannot reintroduce what review has retired, and the
-- decision stays auditable. The importer reads the same registry, so these
-- elements are not re-admitted by a future OSM supplement either.
--
-- Where an OSM element matched two Foursquare rows, both names are listed:
-- those are Foursquare-internal duplicates, which this migration does not
-- address. See KAN-390.
INSERT INTO poi_source_correction
  (source, source_id, visible, name_override, dedupe_name_override, review_note)
VALUES
  ('openstreetmap', 'node/6441622817', 0, NULL, NULL, 'Duplicate of retained Foursquare O Martins. OSM: Restaurante Martins (0.3m).'),
  ('openstreetmap', 'node/5367968460', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Cervejaria Farol / Restaurante Farol. OSM: Farol - Marisqueira Cervejaria (0.6m).'),
  ('openstreetmap', 'node/1408509182', 0, NULL, NULL, 'Duplicate of retained Foursquare In Café. OSM: Café IN (0.6m).'),
  ('openstreetmap', 'node/6823072977', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Gatinho. OSM: O Gatinho (0.9m).'),
  ('openstreetmap', 'node/5580775015', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Martelo. OSM: O Martelo (1.1m).'),
  ('openstreetmap', 'node/1445852641', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Transmontano. OSM: O Transmontano (1.2m).'),
  ('openstreetmap', 'node/1243581259', 0, NULL, NULL, 'Duplicate of retained Foursquare A Colonial. OSM: Pastelaria Colonial (1.3m).'),
  ('openstreetmap', 'node/4707436453', 0, NULL, NULL, 'Duplicate of retained Foursquare Snack-bar Cervejaria Coelho. OSM: Café Coelho (1.5m).'),
  ('openstreetmap', 'node/11035383784', 0, NULL, NULL, 'Duplicate of retained Foursquare Pastelaria Rosmaninho. OSM: O Rosmaninho (1.6m).'),
  ('openstreetmap', 'way/639244532', 0, NULL, NULL, 'Duplicate of retained Foursquare Pedregulho Restaurante. OSM: O Pedregulho (1.8m).'),
  ('openstreetmap', 'node/1563685395', 0, NULL, NULL, 'Duplicate of retained Foursquare Pastelaria Central. OSM: Café Central (2.2m).'),
  ('openstreetmap', 'node/5894779086', 0, NULL, NULL, 'Duplicate of retained Foursquare O Frequente. OSM: Restaurante Frequente (2.3m).'),
  ('openstreetmap', 'node/1296501583', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Alfredo. OSM: O Alfredo (2.3m).'),
  ('openstreetmap', 'node/1538055765', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Boleeiro. OSM: O Boleeiro (2.3m).'),
  ('openstreetmap', 'node/13516725745', 0, NULL, NULL, 'Duplicate of retained Foursquare Campanha Cafe. OSM: Café Campanhã (2.4m).'),
  ('openstreetmap', 'node/1297928680', 0, NULL, NULL, 'Duplicate of retained Foursquare PLF Cafeteria. OSM: Bar PLF (2.4m).'),
  ('openstreetmap', 'node/13099689722', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Palácio. OSM: O Palácio (2.7m).'),
  ('openstreetmap', 'node/11407335469', 0, NULL, NULL, 'Duplicate of retained Foursquare Bar Vitaminas. OSM: Vitaminas Bar (2.7m).'),
  ('openstreetmap', 'way/354704860', 0, NULL, NULL, 'Duplicate of retained Foursquare OffShore Bar. OSM: Bar Offshore (3.1m).'),
  ('openstreetmap', 'node/5572753994', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Regional. OSM: O Regional (3.1m).'),
  ('openstreetmap', 'way/237657505', 0, NULL, NULL, 'Duplicate of retained Foursquare Avenida Cafe. OSM: Café Avenida (3.2m).'),
  ('openstreetmap', 'node/535364817', 0, NULL, NULL, 'Duplicate of retained Foursquare Bar Góis. OSM: Café Gois (3.2m).'),
  ('openstreetmap', 'node/4803588399', 0, NULL, NULL, 'Duplicate of retained Foursquare Café Pastelaria Recanto. OSM: O Recanto (3.4m).'),
  ('openstreetmap', 'node/13512697845', 0, NULL, NULL, 'Duplicate of retained Foursquare Café Java. OSM: Java Café-Restaurante (3.5m).'),
  ('openstreetmap', 'node/2200524204', 0, NULL, NULL, 'Duplicate of retained Foursquare Lugarinho Pastelaria. OSM: Padaria Lugarinho (3.5m).'),
  ('openstreetmap', 'node/2070597631', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Torrão. OSM: O Torrão (3.7m).'),
  ('openstreetmap', 'node/11215568018', 0, NULL, NULL, 'Duplicate of retained Foursquare Pastelaria Turumo. OSM: Turumo - Padaria Pastelaria (3.7m).'),
  ('openstreetmap', 'node/13685924042', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Constantino. OSM: O Constantino (3.8m).'),
  ('openstreetmap', 'way/230051848', 0, NULL, NULL, 'Duplicate of retained Foursquare Cervejaria Mafalda Bar. OSM: Bar da Mafalda (3.8m).'),
  ('openstreetmap', 'node/1491980659', 0, NULL, NULL, 'Duplicate of retained Foursquare Café Restaurante Parque. OSM: O Parque (4.3m).'),
  ('openstreetmap', 'node/2387820843', 0, NULL, NULL, 'Duplicate of retained Foursquare Fronteira Bar. OSM: Bar da Fronteira (4.4m).'),
  ('openstreetmap', 'node/2964330825', 0, NULL, NULL, 'Duplicate of retained Foursquare Tasca A Grelha. OSM: Restaurante "A Grelha" (4.4m).'),
  ('openstreetmap', 'node/1254377401', 0, NULL, NULL, 'Duplicate of retained Foursquare Hamburgo Restaurante. OSM: Restaurante Hamburgo (4.4m).'),
  ('openstreetmap', 'node/5854422758', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Sanzala. OSM: A Sanzala (4.5m).'),
  ('openstreetmap', 'node/3854453155', 0, NULL, NULL, 'Duplicate of retained Foursquare O Paço. OSM: Churrasqueira do Paço (4.6m).'),
  ('openstreetmap', 'node/554152164', 0, NULL, NULL, 'Duplicate of retained Foursquare Caixote Snack Bar. OSM: O Caixote (4.6m).'),
  ('openstreetmap', 'node/13504609679', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Chelsea. OSM: Chelsea - Restaurante Churrasqueira (4.8m).'),
  ('openstreetmap', 'node/1782789982', 0, NULL, NULL, 'Duplicate of retained Foursquare Café do Museu. OSM: Museu Café (4.8m).'),
  ('openstreetmap', 'node/5852302829', 0, NULL, NULL, 'Duplicate of retained Foursquare Chessenta Bar. OSM: Bar CheSsenta (4.9m).'),
  ('openstreetmap', 'node/4621674960', 0, NULL, NULL, 'Duplicate of retained Foursquare Batalha Cafe. OSM: Café Batalha (5.0m).'),
  ('openstreetmap', 'way/282365291', 0, NULL, NULL, 'Duplicate of retained Foursquare A Rotunda. OSM: Restaurante Rotunda (5.0m).'),
  ('openstreetmap', 'node/1696309784', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Rodrigo. OSM: O Rodrigo (5.2m).'),
  ('openstreetmap', 'way/687596451', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante R3. OSM: R3 (5.2m).'),
  ('openstreetmap', 'node/11963404828', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Olaias. OSM: Olaias Restaurante (5.3m).'),
  ('openstreetmap', 'node/2218560198', 0, NULL, NULL, 'Duplicate of retained Foursquare Noiras Bar. OSM: Restaurante Noiras (5.4m).'),
  ('openstreetmap', 'node/1207582573', 0, NULL, NULL, 'Duplicate of retained Foursquare Grao A Grao Bar. OSM: Café O Grão (5.5m).'),
  ('openstreetmap', 'node/8871452626', 0, NULL, NULL, 'Duplicate of retained Foursquare Café da Mata. OSM: Café Snack Bar da Mata (5.6m).'),
  ('openstreetmap', 'way/387486556', 0, NULL, NULL, 'Duplicate of retained Foursquare Café Cruzeiro. OSM: Padaria do Cruzeiro (5.9m).'),
  ('openstreetmap', 'node/9907748927', 0, NULL, NULL, 'Duplicate of retained Foursquare Laguna Bar Restaurante. OSM: Restaurante Laguna (5.9m).'),
  ('openstreetmap', 'node/5774118412', 0, NULL, NULL, 'Duplicate of retained Foursquare Café da Picha. OSM: Restaurante da Picha (5.9m).'),
  ('openstreetmap', 'node/12453652303', 0, NULL, NULL, 'Duplicate of retained Foursquare Majestic Café. OSM: Café Majestic (6.0m).'),
  ('openstreetmap', 'node/4358546491', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Tradicao. OSM: A Tradição (6.0m).'),
  ('openstreetmap', 'way/368374607', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Teimoso. OSM: O Teimoso (6.1m).'),
  ('openstreetmap', 'node/1930252666', 0, NULL, NULL, 'Duplicate of retained Foursquare O Moinho. OSM: Restaurante Moinho (6.1m).'),
  ('openstreetmap', 'node/4361264594', 0, NULL, NULL, 'Duplicate of retained Foursquare O Rei. OSM: Rei - Restaurante e Churrasqueira (6.2m).'),
  ('openstreetmap', 'node/1799589296', 0, NULL, NULL, 'Duplicate of retained Foursquare Pastelaria Torre. OSM: A Torre (6.2m).'),
  ('openstreetmap', 'way/1044804493', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Industrial. OSM: O Industrial (6.2m).'),
  ('openstreetmap', 'node/2498388211', 0, NULL, NULL, 'Duplicate of retained Foursquare O Fernando. OSM: Restaurante Fernando (6.7m).'),
  ('openstreetmap', 'node/13727092900', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurant Elite. OSM: Elite Restaurant & Bar (6.7m).'),
  ('openstreetmap', 'node/3690634296', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Lino. OSM: O Lino (6.7m).'),
  ('openstreetmap', 'node/9942493617', 0, NULL, NULL, 'Duplicate of retained Foursquare Cervejaria Do Heroismo. OSM: Heroismo Cervejaria Marisqueira (6.8m).'),
  ('openstreetmap', 'node/1487261819', 0, NULL, NULL, 'Duplicate of retained Foursquare Confeitaria Davilina. OSM: Davilina - Snack-bar (6.9m).'),
  ('openstreetmap', 'node/8985397421', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Gouveia. OSM: O Gouveia (7.2m).'),
  ('openstreetmap', 'node/11423868637', 0, NULL, NULL, 'Duplicate of retained Foursquare Convento Restaurante. OSM: O Convento (7.2m).'),
  ('openstreetmap', 'node/10710930209', 0, NULL, NULL, 'Duplicate of retained Foursquare O Piriquito. OSM: Café/Restaurante Piriquito (7.2m).'),
  ('openstreetmap', 'node/2319927686', 0, NULL, NULL, 'Duplicate of retained Foursquare O Emigrante. OSM: Restaurante Emigrante (7.6m).'),
  ('openstreetmap', 'way/490145938', 0, NULL, NULL, 'Duplicate of retained Foursquare Bar K. OSM: Gelataria K Bar (7.6m).'),
  ('openstreetmap', 'way/1073578531', 0, NULL, NULL, 'Duplicate of retained Foursquare Penim Bar. OSM: Bar Penim (7.8m).'),
  ('openstreetmap', 'node/1640947346', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Quaresma. OSM: Churrasqueira Quaresma (8.0m).'),
  ('openstreetmap', 'node/6087582720', 0, NULL, NULL, 'Duplicate of retained Foursquare Cervejaria Central. OSM: Restaurante Central (8.0m).'),
  ('openstreetmap', 'node/3078909899', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Pinhal Bar. OSM: Pinhal (8.0m).'),
  ('openstreetmap', 'node/1813847055', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Pauliana. OSM: Churrasqueira Pauliana (8.1m).'),
  ('openstreetmap', 'node/4572013935', 0, NULL, NULL, 'Duplicate of retained Foursquare L7. OSM: Restaurante L7 (8.1m).'),
  ('openstreetmap', 'node/9332557003', 0, NULL, NULL, 'Duplicate of retained Foursquare Cervejaria Do Castelo / Restaurante Castelo. OSM: Castelo Restaurante (8.2m).'),
  ('openstreetmap', 'node/6433928791', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Convite. OSM: O Convite (8.2m).'),
  ('openstreetmap', 'node/14050704701', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Turismo. OSM: Turismo café (8.2m).'),
  ('openstreetmap', 'way/849626342', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Candeeirinho. OSM: O Candeeirinho (8.3m).'),
  ('openstreetmap', 'way/1059980422', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Ponderosa. OSM: A Ponderosa (8.3m).'),
  ('openstreetmap', 'node/12766605419', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Ronca. OSM: O Ronca (8.4m).'),
  ('openstreetmap', 'node/3890995497', 0, NULL, NULL, 'Duplicate of retained Foursquare Bar 21. OSM: 21 (8.4m).'),
  ('openstreetmap', 'node/12237843316', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Botequim. OSM: O Botequim (8.5m).'),
  ('openstreetmap', 'way/563957123', 0, NULL, NULL, 'Duplicate of retained Foursquare O Veleiro. OSM: RESTAURANTE VELEIRO (8.6m).'),
  ('openstreetmap', 'way/335748513', 0, NULL, NULL, 'Duplicate of retained Foursquare Geada Cafe. OSM: Café Geada (8.7m).'),
  ('openstreetmap', 'way/432098029', 0, NULL, NULL, 'Duplicate of retained Foursquare restaurante Trovador. OSM: O Trovador (8.8m).'),
  ('openstreetmap', 'node/4683269119', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Olímpico. OSM: O Olímpico (8.9m).'),
  ('openstreetmap', 'node/2204210340', 0, NULL, NULL, 'Duplicate of retained Foursquare A Serrana. OSM: Confeitaria Serrana (9.0m).'),
  ('openstreetmap', 'node/410064124', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Paulo. OSM: O Paulo (9.0m).'),
  ('openstreetmap', 'node/6294123929', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Churrasqueira Viela. OSM: A Viela (9.0m).'),
  ('openstreetmap', 'node/14075609004', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Viveiro. OSM: O Viveiro (9.1m).'),
  ('openstreetmap', 'node/9834162715', 0, NULL, NULL, 'Duplicate of retained Foursquare Café Onital. OSM: Onital Cervejaria (9.3m).'),
  ('openstreetmap', 'node/13137871908', 0, NULL, NULL, 'Duplicate of retained Foursquare Café Belita. OSM: Café - Mercearia Belita (9.6m).'),
  ('openstreetmap', 'node/5765616927', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Escondidinho. OSM: O Escondidinho (9.6m).'),
  ('openstreetmap', 'node/2665342839', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Helder. OSM: O Helder (9.8m).'),
  ('openstreetmap', 'node/10006780899', 0, NULL, NULL, 'Duplicate of retained Foursquare Aroma Café. OSM: Café Aroma (9.9m).'),
  ('openstreetmap', 'node/1936865570', 0, NULL, NULL, 'Duplicate of retained Foursquare Pastelaria Ribela. OSM: Confeitaria Ribela (10.0m).'),
  ('openstreetmap', 'node/3869643282', 0, NULL, NULL, 'Duplicate of retained Foursquare Café Cappuccino. OSM: Café Restaurante Cappuccino (10.0m).'),
  ('openstreetmap', 'node/4106696613', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante JI. OSM: JI (10.2m).'),
  ('openstreetmap', 'node/2626351701', 0, NULL, NULL, 'Duplicate of retained Foursquare Cervejaria Vianense. OSM: A Vianense (10.2m).'),
  ('openstreetmap', 'node/12324206615', 0, NULL, NULL, 'Duplicate of retained Foursquare Loja Mó. OSM: MO (10.5m).'),
  ('openstreetmap', 'node/12897345667', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Minhoto. OSM: O Minhoto (10.8m).'),
  ('openstreetmap', 'way/721266982', 0, NULL, NULL, 'Duplicate of retained Foursquare Manezinho Restaurante. OSM: café Manezinho (10.8m).'),
  ('openstreetmap', 'node/12292019983', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Daniel. OSM: Daniel Restaurante (10.9m).'),
  ('openstreetmap', 'node/3651247727', 0, NULL, NULL, 'Duplicate of retained Foursquare Madureira. OSM: Restaurante Snack-Bar Madureira''s (11.0m).'),
  ('openstreetmap', 'node/838419829', 0, NULL, NULL, 'Duplicate of retained Foursquare Lagoa Café-Bar. OSM: Café Lagoa (11.0m).'),
  ('openstreetmap', 'node/5914936685', 0, NULL, NULL, 'Duplicate of retained Foursquare O Calhambeque. OSM: Restaurante Calhambeque (11.1m).'),
  ('openstreetmap', 'node/1450668021', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Estrela. OSM: Café Estrela (11.2m).'),
  ('openstreetmap', 'node/3827822169', 0, NULL, NULL, 'Duplicate of retained Foursquare Café Restaurante O Ideal. OSM: Café Ideal (11.4m).'),
  ('openstreetmap', 'node/1366126400', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Tanoeiro. OSM: Tanoeiro Restaurante (11.5m).'),
  ('openstreetmap', 'node/4241354744', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Portucale. OSM: Portucale Restaurant (11.8m).'),
  ('openstreetmap', 'node/2036082068', 0, NULL, NULL, 'Duplicate of retained Foursquare Diploma snack-bar. OSM: Café Diploma (11.8m).'),
  ('openstreetmap', 'node/1767509080', 0, NULL, NULL, 'Duplicate of retained Foursquare Bar Vintri Pub. OSM: Vintri (11.9m).'),
  ('openstreetmap', 'node/13415866635', 0, NULL, NULL, 'Duplicate of retained Foursquare Pizzaria Caprichosa. OSM: Restaurante Caprichosa (12.2m).'),
  ('openstreetmap', 'node/7856868308', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante CaRRoSSeL. OSM: O Carrossel (12.3m).'),
  ('openstreetmap', 'node/4721781259', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Lázaros. OSM: Os Lázaros (12.4m).'),
  ('openstreetmap', 'node/3966487857', 0, NULL, NULL, 'Duplicate of retained Foursquare A Grelha. OSM: Restaurante Grelha (12.4m).'),
  ('openstreetmap', 'node/1605816288', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante 15. OSM: Snack Bar 15 (12.6m).'),
  ('openstreetmap', 'node/1609046760', 0, NULL, NULL, 'Duplicate of retained Foursquare Café Restaurante Muralha. OSM: A Muralha (12.6m).'),
  ('openstreetmap', 'node/11318409648', 0, NULL, NULL, 'Duplicate of retained Foursquare Loja do Vitória. OSM: Vitória Store (12.7m).'),
  ('openstreetmap', 'way/1120638473', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Quintinha. OSM: A Quintinha (12.7m).'),
  ('openstreetmap', 'node/612176539', 0, NULL, NULL, 'Duplicate of retained Foursquare Cafe Restaurante Baltarense. OSM: O Baltarense (12.8m).'),
  ('openstreetmap', 'node/7549623071', 0, NULL, NULL, 'Duplicate of retained Foursquare Café Avenida. OSM: Avenida''s (12.8m).'),
  ('openstreetmap', 'node/9416234190', 0, NULL, NULL, 'Duplicate of retained Foursquare Centro Café Bar. OSM: Café Centro (13.0m).'),
  ('openstreetmap', 'node/8818110745', 0, NULL, NULL, 'Duplicate of retained Foursquare Pastelaria Avenida. OSM: Café Avenida (13.2m).'),
  ('openstreetmap', 'node/11044688256', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante "A Tina". OSM: A TINA Restaurante (13.2m).'),
  ('openstreetmap', 'node/455517446', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante O Bombeiro. OSM: Snack-bar O Bombeiro (13.3m).'),
  ('openstreetmap', 'node/1811984338', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante A Cabana. OSM: O Cabana (13.4m).'),
  ('openstreetmap', 'way/612425595', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Mirante. OSM: O Mirante (13.4m).'),
  ('openstreetmap', 'node/4540126674', 0, NULL, NULL, 'Duplicate of retained Foursquare River Restaurant. OSM: The River (13.5m).'),
  ('openstreetmap', 'node/5045067328', 0, NULL, NULL, 'Duplicate of retained Foursquare Copas Bar. OSM: O Copas (13.5m).'),
  ('openstreetmap', 'node/2725143999', 0, NULL, NULL, 'Duplicate of retained Foursquare Ponsi Pizzeria. OSM: Pizzaria Ponsi (13.5m).'),
  ('openstreetmap', 'node/2218609681', 0, NULL, NULL, 'Duplicate of retained Foursquare Marbelo Restaurante. OSM: Restaurante Marbelo (13.6m).'),
  ('openstreetmap', 'node/4856060814', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Mena. OSM: Da Mena (13.6m).'),
  ('openstreetmap', 'way/348242241', 0, NULL, NULL, 'Duplicate of retained Foursquare Regatinho. OSM: O Regatinho Restaurante e Snack-Bar (13.8m).'),
  ('openstreetmap', 'node/1801739299', 0, NULL, NULL, 'Duplicate of retained Foursquare restaurante conquilha. OSM: "A Conquilha" (14.0m).'),
  ('openstreetmap', 'node/3993056263', 0, NULL, NULL, 'Duplicate of retained Foursquare Pastelaria Tupi. OSM: Tupi - Pastelaria Snack-Bar (14.7m).'),
  ('openstreetmap', 'node/8319099102', 0, NULL, NULL, 'Duplicate of retained Foursquare Café Snack-Bar Gingão. OSM: O Gingão (14.8m).'),
  ('openstreetmap', 'node/4426774599', 0, NULL, NULL, 'Duplicate of retained Foursquare Atlantico Restaurant. OSM: Restaurante Atlântico (14.8m).'),
  ('openstreetmap', 'node/4205246172', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante O Lampião. OSM: a Lampiao (14.9m).'),
  ('openstreetmap', 'node/6709764059', 0, NULL, NULL, 'Duplicate of retained Foursquare Café Europa. OSM: Restaurante “Europa” (15.0m).'),
  ('openstreetmap', 'node/4071475388', 0, NULL, NULL, 'Duplicate of retained Foursquare O Trem. OSM: Café Trem (15.0m).'),
  ('openstreetmap', 'node/8439543353', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Palácio. OSM: O Palácio (15.2m).'),
  ('openstreetmap', 'node/2588836772', 0, NULL, NULL, 'Duplicate of retained Foursquare Tubas Bar. OSM: O Tubas (15.2m).'),
  ('openstreetmap', 'node/14056944901', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Leme. OSM: O Leme (15.2m).'),
  ('openstreetmap', 'node/2931946767', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Curva. OSM: A Curva (15.3m).'),
  ('openstreetmap', 'node/6516582822', 0, NULL, NULL, 'Duplicate of retained Foursquare Café Corotelo. OSM: Corotelo Café (15.3m).'),
  ('openstreetmap', 'node/10845766116', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante "Miguel". OSM: O Miguel (15.9m).'),
  ('openstreetmap', 'node/5337650903', 0, NULL, NULL, 'Duplicate of retained Foursquare O Moinho. OSM: Restaurante Moinho (15.9m).'),
  ('openstreetmap', 'node/4137254384', 0, NULL, NULL, 'Duplicate of retained Foursquare Café Snack-Bar Rumar. OSM: Restaurante Rumar (15.9m).'),
  ('openstreetmap', 'node/7090793685', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Trindade. OSM: Pizzaria Trindade (16.0m).'),
  ('openstreetmap', 'node/1814353145', 0, NULL, NULL, 'Duplicate of retained Foursquare Pastelaria Bantu. OSM: Café Bantu (16.1m).'),
  ('openstreetmap', 'node/13591251501', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Casarão. OSM: O Casarão (16.3m).'),
  ('openstreetmap', 'node/5337650915', 0, NULL, NULL, 'Duplicate of retained Foursquare Cocktail Pastelaria. OSM: Pastelaria Cocktail (16.3m).'),
  ('openstreetmap', 'node/1809861978', 0, NULL, NULL, 'Duplicate of retained Foursquare Anfiteatro Restaurante. OSM: O Anfiteatro (16.3m).'),
  ('openstreetmap', 'node/6428884273', 0, NULL, NULL, 'Duplicate of retained Foursquare Cafe Papagaio. OSM: Snack-Bar Papagaio (16.4m).'),
  ('openstreetmap', 'node/3046024133', 0, NULL, NULL, 'Duplicate of retained Foursquare O Escondidinho. OSM: Restaurante Escondidinho (16.4m).'),
  ('openstreetmap', 'node/3512107130', 0, NULL, NULL, 'Duplicate of retained Foursquare Café Docas Bar. OSM: Docas (16.8m).'),
  ('openstreetmap', 'node/9201706196', 0, NULL, NULL, 'Duplicate of retained Foursquare Stop Restaurante. OSM: Restaurante Stop (16.8m).'),
  ('openstreetmap', 'node/4801952852', 0, NULL, NULL, 'Duplicate of retained Foursquare Café Cota. OSM: Snack Bar O Cota (16.8m).'),
  ('openstreetmap', 'node/1460085163', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Alice. OSM: Churrasqueira Alice (16.9m).'),
  ('openstreetmap', 'way/428807641', 0, NULL, NULL, 'Duplicate of retained Foursquare restaurante da serra. OSM: A Serra (17.0m).'),
  ('openstreetmap', 'way/1107767877', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante O Tapadão. OSM: Churrasqueira do Tapadão (17.1m).'),
  ('openstreetmap', 'node/3612722043', 0, NULL, NULL, 'Duplicate of retained Foursquare Snack-Bar PX. OSM: PX (17.2m).'),
  ('openstreetmap', 'node/6439269620', 0, NULL, NULL, 'Duplicate of retained Foursquare Snack-Bar Pastelaria 2001. OSM: Restaurante e Pastelaria "2001" (17.3m).'),
  ('openstreetmap', 'node/4689067590', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Palermice. OSM: O Palermice (17.5m).'),
  ('openstreetmap', 'node/5744317089', 0, NULL, NULL, 'Duplicate of retained Foursquare Origano Pizzeria. OSM: Pizzeria Origano (17.5m).'),
  ('openstreetmap', 'node/2657812647', 0, NULL, NULL, 'Duplicate of retained Foursquare restaurante lusitano. OSM: O Lusitano (17.6m).'),
  ('openstreetmap', 'node/2937899526', 0, NULL, NULL, 'Duplicate of retained Foursquare Café Locarno. OSM: Locarno - Café Snack-Bar (17.7m).'),
  ('openstreetmap', 'way/292382987', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Flora. OSM: Snack-bar Flora (17.7m).'),
  ('openstreetmap', 'node/1739025671', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Os Laranjeiras. OSM: Os Laranjeiras - Restaurante Churrasqueira (17.8m).'),
  ('openstreetmap', 'node/10111182134', 0, NULL, NULL, 'Duplicate of retained Foursquare Snack Bar Trevo. OSM: O Trevo (17.9m).'),
  ('openstreetmap', 'node/11351361292', 0, NULL, NULL, 'Duplicate of retained Foursquare Café Mundo. OSM: O Mundo (18.0m).'),
  ('openstreetmap', 'node/3937497757', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Américo. OSM: O Américo (18.0m).'),
  ('openstreetmap', 'node/8963044476', 0, NULL, NULL, 'Duplicate of retained Foursquare Templo Café. OSM: Café Templo (18.1m).'),
  ('openstreetmap', 'node/5566016041', 0, NULL, NULL, 'Duplicate of retained Foursquare O Marmita. OSM: A Marmita Restaurante (18.1m).'),
  ('openstreetmap', 'node/1804497642', 0, NULL, NULL, 'Duplicate of retained Foursquare Café Guarany. OSM: Guarany Café-Restaurante (18.6m).'),
  ('openstreetmap', 'way/253988845', 0, NULL, NULL, 'Duplicate of retained Foursquare A Cozinha Cafe Restaurante. OSM: Cozinha (18.7m).'),
  ('openstreetmap', 'node/2758771066', 0, NULL, NULL, 'Duplicate of retained Foursquare restaurante cacilheiro. OSM: O Cacilheiro (18.9m).'),
  ('openstreetmap', 'node/4787062333', 0, NULL, NULL, 'Duplicate of retained Foursquare Café "O Tunel". OSM: Snack Bar O Túnel (18.9m).'),
  ('openstreetmap', 'node/2631084264', 0, NULL, NULL, 'Duplicate of retained Foursquare Café - Pastelaria Martinik. OSM: Snack-Bar Martinik (19.0m).'),
  ('openstreetmap', 'node/4319526144', 0, NULL, NULL, 'Duplicate of retained Foursquare JB. OSM: JB Bar (19.3m).'),
  ('openstreetmap', 'node/1913242767', 0, NULL, NULL, 'Duplicate of retained Foursquare Restaurante Querida. OSM: Churrasqueira Querida (19.5m).'),
  ('openstreetmap', 'node/2806711601', 0, NULL, NULL, 'Duplicate of retained Foursquare Café Esquimó. OSM: Café Gelataria Esquimó (19.9m).')
ON CONFLICT(source, source_id) DO UPDATE SET
  visible = excluded.visible,
  name_override = excluded.name_override,
  dedupe_name_override = excluded.dedupe_name_override,
  review_note = excluded.review_note;
