"""
KAN-196 — train the on-device POI text classifier (run in Google Colab).

Produces `poi_classifier.tflite` (TFLite + embedded metadata/vocab) loadable by
MediaPipe Tasks `TextClassifier` on Android AND iOS — no per-device hardware
gate, runs offline on essentially all phones.

────────────────────────────────────────────────────────────────────────────
HOW TO RUN (Colab, ~5 min, free):
  1. New Colab notebook → Runtime → ensure a CPU runtime is fine.
  2. Upload train.csv + validation.csv (generated by generate_dataset.py).
  3. Paste this file's contents into a cell (or `%run train_colab.py`) and run.
  4. Download the emitted `poi_classifier.tflite` and `labels.txt`.
  5. Commit them to the repo (the native module bundles the .tflite as an asset).

NOTE on Python: mediapipe-model-maker needs Python 3.11/3.12 (Colab default is
fine). It will NOT install on Python 3.14.
────────────────────────────────────────────────────────────────────────────
"""

# 1) Install (Colab):
#    !pip install -q mediapipe-model-maker

from mediapipe_model_maker import text_classifier


def main():
    # Average Word Embedding: tiny (~1-5 MB), fast on CPU, great for short
    # single-sentence titles. (BERT is available but far larger/slower and
    # unnecessary for a 17-way short-text task.)
    spec = text_classifier.SupportedModels.AVERAGE_WORD_EMBEDDING_CLASSIFIER

    train_data = text_classifier.Dataset.from_csv(
        filename="train.csv", text_column="text", label_column="label"
    )
    val_data = text_classifier.Dataset.from_csv(
        filename="validation.csv", text_column="text", label_column="label"
    )

    hparams = text_classifier.AverageWordEmbeddingHParams(
        epochs=15,
        batch_size=32,
        learning_rate=0.001,
        export_dir="exported_model",
    )
    options = text_classifier.TextClassifierOptions(
        supported_model=spec, hparams=hparams
    )

    model = text_classifier.TextClassifier.create(train_data, val_data, options)

    loss, acc = model.evaluate(val_data)
    print(f"Validation loss={loss:.4f} accuracy={acc:.4f}")

    # Exports exported_model/model.tflite with metadata + vocab baked in.
    model.export_model(model_name="poi_classifier.tflite")
    model.export_labels(export_dir="exported_model")
    print("Wrote exported_model/poi_classifier.tflite and labels.txt")


if __name__ == "__main__":
    main()
